# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculation.proto\x12\x04grpc\"w\n\x0fSolutionRequest\x12\x0e\n\x06wellId\x18\x01 \x01(\t\x12\x11\n\tequations\x18\x02 \x03(\t\x12\x15\n\rvariableNames\x18\x03 \x03(\t\x12\x14\n\x0cinitialGuess\x18\x04 \x03(\x01\x12\x14\n\x0csolverMethod\x18\x05 \x01(\t\"}\n\x10SolutionResponse\x12\x0e\n\x06wellId\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x11\n\tvariables\x18\x03 \x03(\x01\x12\x12\n\niterations\x18\x04 \x01(\x05\x12\x10\n\x08residual\x18\x05 \x01(\x01\x12\x0f\n\x07message\x18\x06 \x01(\t\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x9f\x01\n\x12LiquidVolumeSolver\x12\x45\n\x14SolveVolumeEquations\x12\x15.grpc.SolutionRequest\x1a\x16.grpc.SolutionResponse\x12\x42\n\x0bHealthCheck\x12\x18.grpc.HealthCheckRequest\x1a\x19.grpc.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOLUTIONREQUEST']._serialized_start=27
  _globals['_SOLUTIONREQUEST']._serialized_end=146
  _globals['_SOLUTIONRESPONSE']._serialized_start=148
  _globals['_SOLUTIONRESPONSE']._serialized_end=273
  _globals['_HEALTHCHECKREQUEST']._serialized_start=275
  _globals['_HEALTHCHECKREQUEST']._serialized_end=295
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=297
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=334
  _globals['_LIQUIDVOLUMESOLVER']._serialized_start=337
  _globals['_LIQUIDVOLUMESOLVER']._serialized_end=496
# @@protoc_insertion_point(module_scope)
